server:
  port: 8181
spring:
  application:
    name: SpringBootCassandraJpa
  data:
    cassandra:
      port: 9042
      keyspace-name: springbootcassandradb
      contact-points: 127.0.0.1
      schema-action: create_if_not_exists
      username: cassandra
      password: cassandra